"""import batches

Revision ID: ea8975536d41
Revises: 57ea0170aa1e
Create Date: 2026-09-28 17:42:07.576013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8975536d41'
down_revision: Union[str, Sequence[str], None] = '57ea0170aa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='DRAFT', nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('replace_stages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idp_retries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('apply_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("file_format IN ('XLSX', 'XLS', 'CSV', 'JSON')", name=op.f('chk_import_batch_format')),
    sa.CheckConstraint("status = 'APPLYING' OR (lease_until IS NULL AND worker_id IS NULL)", name=op.f('chk_import_batch_lease')),
    sa.CheckConstraint("status IN ('DRAFT', 'APPLYING', 'APPLIED')", name=op.f('chk_import_batch_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_batches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_import_batches_workflow_id_workflows'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index('ix_import_batches_status', 'import_batches', ['status', 'id'], unique=False)
    op.create_table('import_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_sheets_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_sheets')),
    sa.UniqueConstraint('batch_id', 'number', name=op.f('uq_import_sheets_batch_id_number'))
    )
    op.create_index(op.f('ix_import_sheets_batch_id'), 'import_sheets', ['batch_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('group_key', sa.String(length=40), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('replace_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manager_choice', sa.String(length=255), nullable=True),
    sa.Column('contacts_target', sa.String(length=60), nullable=True),
    sa.Column('excluded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('digest', sa.String(length=64), server_default='', nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('result_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['import_sheets.id'], name=op.f('fk_import_rows_sheet_id_import_sheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('sheet_id', 'number', name=op.f('uq_import_rows_sheet_id_number'))
    )
    op.create_index('ix_import_rows_batch_group', 'import_rows', ['batch_id', 'group_key'], unique=False)
    op.create_index('ix_import_rows_batch_result', 'import_rows', ['batch_id', 'result'], unique=False)
    op.create_index('ix_import_rows_batch_status', 'import_rows', ['batch_id', 'status'], unique=False)
    op.create_table('import_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_signed_at', sa.Date(), nullable=True),
    sa.Column('contract_valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attachment_id IS NOT NULL OR document_id IS NOT NULL', name=op.f('chk_import_file_target')),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_import_files_attachment_id_attachments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['interaction_documents.id'], name=op.f('fk_import_files_document_id_interaction_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['import_rows.id'], name=op.f('fk_import_files_row_id_import_rows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_import_files_stage_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_files'))
    )
    op.create_index(op.f('ix_import_files_attachment_id'), 'import_files', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_import_files_row_id'), 'import_files', ['row_id'], unique=False)
    op.alter_column('interaction_documents', 'attachment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint(
        "chk_document_file_or_contract",
        "interaction_documents",
        "attachment_id IS NOT NULL OR kind = 'CONTRACT'",
    )
    # системные причины «Заменена импортом» (В7): исход DONE, в потерях не считаются
    op.execute(
        """
        INSERT INTO close_reasons (code, label, level, outcome, needs_comment, is_system)
        VALUES
            ('REPLACED_BY_IMPORT_BEFORE', 'Заменена импортом', 'INTERACTION_BEFORE_SIGNING', 'DONE', false, true),
            ('REPLACED_BY_IMPORT_AFTER', 'Заменена импортом', 'INTERACTION_AFTER_SIGNING', 'DONE', false, true),
            ('REPLACED_BY_IMPORT', 'Заменена импортом', 'BRANCH', 'DONE', false, true)
        ON CONFLICT (code) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # на них могли сослаться - тогда downgrade падает, как любая миграция данных
    op.execute(
        "DELETE FROM close_reasons WHERE code IN "
        "('REPLACED_BY_IMPORT_BEFORE', 'REPLACED_BY_IMPORT_AFTER', 'REPLACED_BY_IMPORT')"
    )
    op.drop_constraint(
        "chk_document_file_or_contract", "interaction_documents", type_="check"
    )
    op.alter_column('interaction_documents', 'attachment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_import_files_row_id'), table_name='import_files')
    op.drop_index(op.f('ix_import_files_attachment_id'), table_name='import_files')
    op.drop_table('import_files')
    op.drop_index('ix_import_rows_batch_status', table_name='import_rows')
    op.drop_index('ix_import_rows_batch_result', table_name='import_rows')
    op.drop_index('ix_import_rows_batch_group', table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_sheets_batch_id'), table_name='import_sheets')
    op.drop_table('import_sheets')
    op.drop_index('ix_import_batches_status', table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
