from enum import StrEnum
from typing import Any

from sqlalchemy import BigInteger, CheckConstraint, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from quoll.db import Base, created_at_dt


class ActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"


class TargetType(StrEnum):
    MANAGER = "MANAGER"
    SUPERVISER = "SUPERVISER"
    INTERACTION = "INTERACTION"
    USER = "USER"
    STAGE = "STAGE"
    WORKFLOW = "WORKFLOW"
    TRANSITION = "TRANSITION"
    REQUEST = "REQUEST"
    DOCUMENT = "DOCUMENT"
    ATTACHMENT = "ATTACHMENT"
    DIRECTION = "DIRECTION"
    PRODUCT = "PRODUCT"
    PROGRAM = "PROGRAM"
    CONTACT = "CONTACT"
    SPECIALTY = "SPECIALTY"
    UNIVERSITY = "UNIVERSITY"
    VENDOR = "VENDOR"
    DOCUMENT_KIND = "DOCUMENT_KIND"
    CLOSE_REASON = "CLOSE_REASON"
    SUPPLEMENTARY_AGREEMENT = "SUPPLEMENTARY_AGREEMENT"


class AuditEventType(StrEnum):
    SUBORDINATE_ASSIGNED = "SUBORDINATE_ASSIGNED"
    SUBORDINATE_RELEASED = "SUBORDINATE_RELEASED"
    SUBORDINATE_TRANSFERRED = "SUBORDINATE_TRANSFERRED"
    SUBORDINATE_ADOPTED = "SUBORDINATE_ADOPTED"
    WORKLOAD_STATUS_CHANGED = "WORKLOAD_STATUS_CHANGED"
    CAPACITY_LIMIT_CHANGED = "CAPACITY_LIMIT_CHANGED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_REACTIVATED = "USER_REACTIVATED"
    PROJECT_REASSIGNED = "PROJECT_REASSIGNED"
    INTERACTION_PAUSED = "INTERACTION_PAUSED"
    INTERACTION_UNPAUSED = "INTERACTION_UNPAUSED"
    ROLE_TRANSITIONED = "ROLE_TRANSITIONED"
    ROLE_TRANSITION_BLOCKED = "ROLE_TRANSITION_BLOCKED"
    ROLE_TRANSITION_CANCELLED = "ROLE_TRANSITION_CANCELLED"
    STAGE_CREATED = "STAGE_CREATED"
    STAGE_UPDATED = "STAGE_UPDATED"
    STAGE_DELETED = "STAGE_DELETED"
    STAGE_SEMANTICS_CHANGED = "STAGE_SEMANTICS_CHANGED"
    STAGE_TRANSITIONED = "STAGE_TRANSITIONED"
    WORKFLOW_PUBLISHED = "WORKFLOW_PUBLISHED"
    ROLE_MAPPING_CONFLICT_DETECTED = "ROLE_MAPPING_CONFLICT_DETECTED"
    ROLE_MAPPING_CONFLICT_RESOLVED = "ROLE_MAPPING_CONFLICT_RESOLVED"
    SUPERVISOR_OFFBOARDED = "SUPERVISOR_OFFBOARDED"
    PAUSE_EXPIRED_SATURATED = "PAUSE_EXPIRED_SATURATED"
    STAGE_ARCHIVED = "STAGE_ARCHIVED"
    START_STAGE_CHANGED = "START_STAGE_CHANGED"
    TRANSITION_CREATED = "TRANSITION_CREATED"
    TRANSITION_UPDATED = "TRANSITION_UPDATED"
    TRANSITION_DEACTIVATED = "TRANSITION_DEACTIVATED"
    TRANSITION_DELETED = "TRANSITION_DELETED"
    WORKFLOW_DELETED = "WORKFLOW_DELETED"
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_UPDATED = "WORKFLOW_UPDATED"
    ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED"
    ATTACHMENT_DELETED = "ATTACHMENT_DELETED"
    TEMPLATE_ATTACHMENT_LINKED = "TEMPLATE_ATTACHMENT_LINKED"
    TEMPLATE_ATTACHMENT_UNLINKED = "TEMPLATE_ATTACHMENT_UNLINKED"
    PROJECT_CLOSED = "PROJECT_CLOSED"
    PROJECT_REOPENED = "PROJECT_REOPENED"
    PROJECT_TRANSFER_REQUESTED = "PROJECT_TRANSFER_REQUESTED"
    PROJECT_TRANSFER_APPROVED = "PROJECT_TRANSFER_APPROVED"
    PROJECT_TRANSFER_REJECTED = "PROJECT_TRANSFER_REJECTED"
    PROJECT_CLOSE_REQUESTED = "PROJECT_CLOSE_REQUESTED"
    PROJECT_CLOSE_APPROVED = "PROJECT_CLOSE_APPROVED"
    PROJECT_CLOSE_REJECTED = "PROJECT_CLOSE_REJECTED"
    REQUEST_CANCELLED = "REQUEST_CANCELLED"
    DOCUMENT_ATTACHED = "DOCUMENT_ATTACHED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    INTERACTION_UPDATED = "INTERACTION_UPDATED"
    INTERACTION_CANCELLED = "INTERACTION_CANCELLED"
    INTERACTION_SLOT_CHANGED = "INTERACTION_SLOT_CHANGED"
    INTERACTION_SETTINGS_CHANGED = "INTERACTION_SETTINGS_CHANGED"
    BRANCH_PAUSED = "BRANCH_PAUSED"
    BRANCH_UNPAUSED = "BRANCH_UNPAUSED"
    SA_OPENED = "SA_OPENED"
    SA_UPDATED = "SA_UPDATED"
    SA_ACTION_ADDED = "SA_ACTION_ADDED"
    SA_ACTION_REMOVED = "SA_ACTION_REMOVED"
    SA_SUBMITTED = "SA_SUBMITTED"
    SA_RETURNED = "SA_RETURNED"
    SA_APPROVED = "SA_APPROVED"
    SA_REJECTED = "SA_REJECTED"
    SA_CANCELLED = "SA_CANCELLED"
    SIDE_POINTER_STARTED = "SIDE_POINTER_STARTED"
    SIDE_POINTER_FINISHED = "SIDE_POINTER_FINISHED"
    SIDE_POINTER_CANCELLED = "SIDE_POINTER_CANCELLED"
    LICENSE_EXTENDED = "LICENSE_EXTENDED"
    CONTRACT_EXTENDED = "CONTRACT_EXTENDED"
    USER_UPDATED = "USER_UPDATED"
    PROJECT_DECLINED = "PROJECT_DECLINED"
    STAGE_VALUES_CHANGED = "STAGE_VALUES_CHANGED"
    TRANSITION_APPROVAL_REQUESTED = "TRANSITION_APPROVAL_REQUESTED"
    TRANSITION_APPROVED = "TRANSITION_APPROVED"
    TRANSITION_REJECTED = "TRANSITION_REJECTED"
    DOCUMENT_APPROVED = "DOCUMENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    WORKFLOW_CHANGE_REQUESTED = "WORKFLOW_CHANGE_REQUESTED"
    WORKFLOW_CHANGE_DECIDED = "WORKFLOW_CHANGE_DECIDED"
    CATALOG_ITEM_CREATED = "CATALOG_ITEM_CREATED"
    CATALOG_ITEM_UPDATED = "CATALOG_ITEM_UPDATED"
    CATALOG_ITEM_DELETED = "CATALOG_ITEM_DELETED"
    CONTRACT_PRODUCTS_CHANGED = "CONTRACT_PRODUCTS_CHANGED"
    BRANCHES_OPENED = "BRANCHES_OPENED"
    BRANCH_TRANSITIONED = "BRANCH_TRANSITIONED"
    BRANCH_CLOSED = "BRANCH_CLOSED"


class AuditLog(Base):
    """Журнал действий, только на добавление.

    UPDATE, DELETE и TRUNCATE запрещены триггером, поэтому тут нет updated_at
    """

    __table_args__ = (
        CheckConstraint(
            "(actor_type = 'SYSTEM' AND actor_id IS NULL) OR "
            "(actor_type = 'USER' AND actor_id IS NOT NULL)",
            name="chk_audit_actor_invariants",
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    actor_type: Mapped[str] = mapped_column(String(20), index=True)
    actor_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    target_type: Mapped[str] = mapped_column(String(30), index=True)
    target_id: Mapped[str] = mapped_column(String(255), index=True)
    event_type: Mapped[str] = mapped_column(String(50), index=True)
    old_value: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    new_value: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[created_at_dt] = mapped_column(index=True)
